contributing.md create
chec/commercejs-nextjs-demo-store pull request #107
Opened 2020-10-03 18:06 UTC by LuizHAP

Fix #62

2020-10-04 20:48 UTC, jaepass requested changes
Thanks Luiz for the PR. Would be great to also specify Commerce.js where applicable in the contributing guide.

2020-10-04 20:48 UTC, jaepass commented on CONTRIBUTING.md
> +## Pull Request Process
These steps do not apply to the project entirely. Would be great to edit to include steps like forking, cloning of the project and making the PR.

2020-10-04 20:48 UTC, jaepass commented on CONTRIBUTING.md
> +reported by contacting the project team at [INSERT EMAIL ADDRESS]. All
Include our email hello@commercejs.com

2020-10-04 22:42 UTC, LuizHAP commented
fixed @jaepass

2020-10-04 23:37 UTC, jaepass commented
Hi Luiz, apologies but I can't accept the changes as is for this project. Feel free to have a read of this [contributing guide](https://github.com/chec/commerce.js/blob/master/CONTRIBUTING.md) to draw from. Good suggestion might also be to spin up this project and test out how to contribute.

2020-10-05 00:02 UTC, LuizHAP commented
@jaepass 
So I can go up the informed link and add the information that is in it, is that it?

2020-10-05 03:55 UTC, jaepass commented
Hi @LuizHAP not just extract the exact info but use as a reference to apply to this project specifically. I'll close this pr for the time being please feel free to open another one when it is ready thank you.

2020-10-05 03:55 UTC, closed without merging