Fix Loading Customer Data
chec/commercejs-nextjs-demo-store pull request #202
Opened 2021-06-01 00:14 UTC by PaitoAnderson

Test Procedure:
1) Login
2) Reload Page
3) Check if can still can load `/account`

2021-06-01 00:34 UTC, jaepass commented
Nice thanks for the PR! Works well with persisting the customer! There's a slight delay in checking if the customer exists when refreshing the page so there's a split second where the logged out screen shows. It's pretty minor but I'm not sure what the fix is at this point.

2021-06-01 22:04 UTC, jaepass requested changes
Nice, thanks for the PR! Works well with persisting the customer! There's a slight delay in checking if the customer exists when refreshing the page so there's a split second where the logged out screen shows. It's pretty minor but I'm not sure what the fix is at this point.

2021-06-02 00:52 UTC, PaitoAnderson commented
@jaepass Good point, I didn't notice that.

Let me know if you think this is a good approach, my thought process was these parts are far apart so I definitely need to use redux, but I didn't want to mix a `isLoading` prop that's only for UI in the `customer` data, so I created another `loading` object that can be potentially be used for keeping the loading state of other redux items too.

2021-06-02 16:31 UTC, jaepass commented
Awesome, thank you @PaitoAnderson!! Let me test this out as soon as I can!

2021-06-02 19:20 UTC, jaepass reviewed
LGTM, I've just added some minor changes. Happy to merge after! Thank you again for the contributions!

2021-06-02 19:20 UTC, jaepass commented on pages/account/index.js
> +      return <TemplatePage page={ {message: 'Loading'} } />
```suggestion
      return <TemplatePage page={  { message: 'Loading...' }  } />
```

2021-06-02 19:20 UTC, jaepass commented on pages/account/[id].js
> +    return <TemplatePage page={ {message: 'Loading'} } />
```suggestion
    return <TemplatePage page={  { message: 'Loading...' }  } />
```

2021-06-02 19:26 UTC, PaitoAnderson commented
Thanks for the quick review!

2021-06-02 19:55 UTC, merged